# Generated by Django 3.2.8 on 2021-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20211121_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('cus_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
